### ISSUE TITLE
Not all funding spaces captured in change request form

### ISSUE THREAD

**Issue by bamader** [ctoec/data-collection#1168] opened 2021-02-09 16:53 UTC

**Comment by JordanGuinn** [comment] 2021-02-10 16:45
Same with this ticket - I see this is a direct duplicate of https://github.com/ctoec/data-collection/issues/1154, so the creation of this only adds confusion as to the progress of things in ZenHub.

**Closed by JordanGuinn** 2021-02-10 16:45 UTC
Labels: bug, dev-team

**Comment by bamader** [comment] 2021-02-10 16:47
@JordanGuinn this could totally be my bad. I went to work on these tickets yesterday, and when I opened the PRs for them, I couldn't find the tickets in github, just the ones in zenhub (which we said not to link to). So I made these in github just for things to put in the associated tickets section. Sorry for the confusion! For the future, does zenhub automatically create github tickets?

**Comment by JordanGuinn** [comment] 2021-02-10 17:12
No worries!  Things happen 🙂

And yes!  Zenhub is simply a UI around GitHub, so tickets present in Zenhub by nature **must** exist in GitHub.  There should be a `View this Issue on GitHub` link in the lower right-hand section of the Zenhub ticket that'll allow you to get there directly.
