### ISSUE TITLE
Set up test data visualization tool

### ISSUE THREAD

**Issue by kmagida110** [ctoec/data-collection#1066] opened 2021-01-15 21:00 UTC
Acceptance Criteria:

- Platform is accessible from the internet
- No associated cost to tool, AWS cost is <$10 month
- Ability to easily add data to tool

**Comment by JordanGuinn** [comment] 2021-01-19 21:34
Closing, as this is a duplicate of https://app.zenhub.com/workspaces/ece-dev-board-5ff506028d35f30012e0e937/issues/ctoec/data-collection/1080undefined

**Closed by JordanGuinn** 2021-01-19 21:34 UTC
Labels: data-integration-viz, dev-team
