### ISSUE TITLE
Remove date default to today for birthdate fields

### ISSUE THREAD

**Issue by RyanHansz** [ctoec/data-collection#659] opened 2020-11-03 15:01 UTC
Also, birthdate as one word.
<img width="339" alt="Screen Shot 2020-11-03 at 10 01 41 AM" src="https://user-images.githubusercontent.com/63253539/98001814-a2a8e680-1dbb-11eb-9067-c58c90afaad8.png">

**Comment by mmazanec22** [comment] 2020-11-17 16:01
Closing because this is a duplicate of #697

**Closed by mmazanec22** 2020-11-17 16:01 UTC
Labels: needs points
