### ISSUE TITLE
Log children with validation errors in `enrollment-reports/check` response

### ISSUE THREAD

**Issue by jlhogan** [ctoec/data-collection#1191] opened 2021-02-22 16:17 UTC
## Context

When debugging issues with upload, it's not always totally clear _why_ a given row has an error in the given column. 

## AC
- Children with validation errors are logged if exist in enrollment-report/check endpoint to enable easier debugging of user upload issues without requiring user to send spreadsheet to me to recreate

**Comment by JordanGuinn** [comment] 2021-03-23 03:17
Is this a duplicate of https://github.com/ctoec/data-collection/issues/1212?

**Comment by JordanGuinn** [comment] 2021-04-14 16:08
We're doing this now thanks to https://github.com/ctoec/data-collection/issues/1212, so gonna mark this as completed.

**Closed by JordanGuinn** 2021-04-14 16:08 UTC
Labels: dev-team
